site_name: Python VoIP
repo_url: https://github.com/codingjoe/VoIP
watch:
  - docs
  - voip
nav:
  - Home:
      - Quickstart: index.md
      - Cookbook: cookbook.md
  - Features:
      - Feature Roadmap: feature_roadmap.md
      - RFC Implementation Status: rfc_status.md
  - API Reference:
      - Calls: calls.md
      - RTP: rtp.md
      - SDP: sdp.md
      - SIP: sip.md
  - Changelog: https://github.com/codingjoe/VoIP/releases
  - Community Support: https://github.com/codingjoe/VoIP/discussions
plugins:
  - autorefs
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: true
          options:
            docstring_style: google
            show_root_heading: true
            heading_level: 3
          inventories:
            - https://docs.python.org/3/objects.inv
theme:
  name: material
  logo: images/icon.svg
  palette:
    - media: "(prefers-color-scheme)"
      primary: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      primary: yellow
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: yellow
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.select
    - content.code.copy
    - navigation.tabs
    - search.suggest
    - search.share
markdown_extensions:
  - github-callouts
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
